### ISSUE TITLE
上传不成功

### ISSUE THREAD

**Issue by geekdada** [ghostchina/Ghost-0.4.1-qiniu#1]
博文里图片上传后返回的链接是404，但是博客后台横幅照片上传后能够显示，七牛那边的设置没有任何问题。不知道有没有办法看看log或者看看上传后七牛有没有返回什么东西？

**Comment by wangsai** [comment]
上传的图片会返回一个链接地址，你打开浏览器的调试工具，看看返回的链接是否正确，再检查后台是否有对应链接地址的图片存在。
例如设置为：
root: '/images/', //文件存储在哪个目录。可以设置为 `/` 表示存储在根目录
prefix: 'http://cdn.my-domainname.com'  //上传的文件的 URL 前缀，可以是你自己绑定的二级域名或者七牛云默认分配的二级域名。文件最中的 URL 为：prefix + root + md5(file) + extension

最后可以获得的图片地址为：
http://cdn.my-domainname.com/images/a/ab/dqwerqwetetqwedfasdf.png

**Comment by geekdada** [comment]
那个链接404，七牛那边也找不到对应的文件。
奇怪的是在Dashboard里上传的主页大图可以显示，没问题。

开启 2014年3月1日 at 上午12:30:35, 王赛 (notifications@github.com) 写:

上传的图片会返回一个链接地址，你打开浏览器的调试工具，看看返回的链接是否正确，再检查后台是否有对应链接地址的图片存在。
例如设置为：
root: '/images/', //文件存储在哪个目录。可以设置为 / 表示存储在根目录
prefix: 'http://cdn.my-domainname.com' //上传的文件的 URL 前缀，可以是你自己绑定的二级域名或者七牛云默认分配的二级域名。文件最中的 URL 为：prefix + root + md5(file) + extension

最后可以获得的图片地址为：
http://cdn.my-domainname.com/images/a/ab/dqwerqwetetqwedfasdf.png

**Comment by wangsai** [comment]
dashboard 里上传的大图能在七牛服务器上找到吗？

**Comment by geekdada** [comment]
可以

开启 2014年3月1日 at 上午12:40:18, 王赛 (notifications@github.com) 写:

dashboard 里上传的大图能在七牛服务器上找到吗？

**Comment by wangsai** [comment]
博文里图片上传后返回的链接是正确的链接格式吗？先不管链接是否能够打开或者404之类的。你把链接贴出来

**Comment by geekdada** [comment]
http://dn-dada.qbox.me/images/c/e2/31176105860e2d73281305a25fe58.jpg

开启 2014年3月1日 at 上午12:46:32, 王赛 (notifications@github.com) 写:

博文里图片上传后返回的链接是正确的链接格式吗？先不管链接是否能够打开或者404之类的。你把链接贴出来

**Comment by maooson** [comment]
遇到同样的问题，上传图片后，链接地址生成了，但在七牛空间找不到图片，返回的链接状态是404，问题是一开始是正常的，是不是有什么过期策略导致的无法正常上传？

**Comment by wangsai** [comment]
你好，

这个问题有同学报告过，由于近期事情比较多，查找、解决问题的进度较慢，建议先不要用上传到七牛的版本，等问题解决后欢迎再使用！

发件人: maooson [mailto:notifications@github.com] 
发送时间: 2014年3月17日 17:16
收件人: ghostchina/Ghost-0.4.1-qiniu
抄送: 王赛
主题: Re: [Ghost-0.4.1-qiniu] 上传不成功 (#1)

遇到同样的问题，上传图片后，链接地址生成了，但在七牛空间找不到图片，返回的链接状态是404，问题是一开始是正常的，是不是有什么过期策略导致的无法正常上传？

**Comment by geekdada** [comment]
支持一下 👍--李一航Roy LiSent using CloudMagicOn Mon, Mar 17, 2014 at 5:19 PM,  ghostchina/Ghost-0.4.1-qiniu reply@reply.github.com wrote:            你好，

这个问题有同学报告过，由于近期事情比较多，查找、解决问题的进度较慢，建议先不要用上传到七牛的版本，等问题解决后欢迎再使用！

发件人: maooson [mailto:notifications@github.com] 

发送时间: 2014年3月17日 17:16

收件人: ghostchina/Ghost-0.4.1-qiniu

抄送: 王赛

主题: Re: [Ghost-0.4.1-qiniu] 上传不成功 (#1)

遇到同样的问题，上传图片后，链接地址生成了，但在七牛空间找不到图片，返回的链接状态是404，问题是一开始是正常的，是不是有什么过期策略导致的无法正常上传？

**Comment by tairan** [comment]
这个问题依然存在， 最近有什么新的解决方案吗？

**Comment by wangsai** [comment]
@tairan @geekdada 已经升级到0.4.2 版本，解决了0.4.1版本中出现的问题，请各位测试，欢迎反馈！

**Comment by wangsai** [comment]
@maooson

**Comment by maooson** [comment]
好的，多谢

**Comment by geekdada** [comment]
非常感谢，去试试
